# ==============================================================
# sql_client.py — MySQL connection + safe query execution
# ==============================================================

import os
from sqlalchemy import create_engine, text
from dotenv import load_dotenv

load_dotenv()

# ==============================================================
# Engine (singleton — created once, reused everywhere)
# ==============================================================

_engine = None

def get_engine():
    """
    Returns a singleton SQLAlchemy engine.
    Created once and reused across all queries.

    Two modes:
      - Local  → MYSQL_SSL=false (default) — no SSL needed
      - Cloud  → MYSQL_SSL=true            — SSL required (Aiven)
    """
    global _engine
    if _engine is None:
        user     = os.getenv("MYSQL_USER")
        password = os.getenv("MYSQL_PASSWORD")
        host     = os.getenv("MYSQL_HOST", "localhost")
        port     = os.getenv("MYSQL_PORT", "3306")
        db       = os.getenv("MYSQL_DB")

        connection_string = (
            f"mysql+pymysql://{user}:{password}@{host}:{port}/{db}"
        )

        ssl_required = os.getenv("MYSQL_SSL", "false").lower() == "true"

        if ssl_required:
            
            print(f"☁️ MySQL Cloud → {host}:{port}/{db}")
            _engine = create_engine(
                connection_string,
                connect_args={"ssl": {"ssl_mode": "REQUIRED"}},
                pool_pre_ping=True,   
                pool_recycle=3600     
            )
        else:
            
            print(f"🖥️ MySQL Local → {host}:{port}/{db}")
            _engine = create_engine(
                connection_string,
                pool_pre_ping=True,
                pool_recycle=3600
            )

    return _engine


# ==============================================================
# Safety Guards
# ==============================================================

_FORBIDDEN_READ_KEYWORDS = {
    "drop", "delete", "update", "insert",
    "alter", "truncate", "replace", "create",
    "grant", "revoke", "exec", "execute"
}

def is_safe_select(query: str) -> bool:
    """
    Validates that the query is a read-only SELECT.
    Blocks any mutation or destructive SQL.

    Returns True if safe, False otherwise.

    Examples:
        is_safe_select("SELECT * FROM orders WHERE order_id = 5") → True
        is_safe_select("DROP TABLE orders")                        → False
    """
    cleaned = query.strip().lower()

    
    if not cleaned.startswith("select"):
        return False

    
    for word in _FORBIDDEN_READ_KEYWORDS:
        if word in cleaned:
            return False

    return True


def is_safe_insert(query: str) -> bool:
    """
    Validates that the query is a safe INSERT only.
    Only allowed on return_requests and complaints tables.
    Blocks any other table modification.

    Returns True if safe, False otherwise.
    """
    cleaned = query.strip().lower()

   
    if not cleaned.startswith("insert"):
        return False

    
    allowed_tables = ["return_requests", "complaints"]
    if not any(table in cleaned for table in allowed_tables):
        return False

    return True


# ==============================================================
# Query Executor — READ only
# ==============================================================

def run_query(query: str) -> list[dict] | str:
    """
    Safely executes a SELECT query and returns rows.

    Args:
        query (str): SQL SELECT query — generated by the LLM.

    Returns:
        list[dict]: Rows as list of dictionaries if successful.
        str:        Error or warning message if failed.

    Example:
        run_query("SELECT * FROM orders WHERE order_id = 5")
        → [{"order_id": 5, "status": "shipped", ...}]
    """
    
    if not is_safe_select(query):
        return "❌ Query blocked: only SELECT statements are allowed."

    try:
        engine = get_engine()
        with engine.connect() as conn:
            result = conn.execute(text(query))
            
            rows = [dict(row._mapping) for row in result]

        if not rows:
            return "⚠️ No results found."

        return rows

    except Exception as e:
        return f"❌ SQL Error: {str(e)}"


# ==============================================================
# Action Executor — WRITE only (returns + complaints)
# ==============================================================

def run_action(query: str, params: dict = None) -> dict:
    """
    Safely executes an INSERT query for customer actions.
    Only allowed on return_requests and complaints tables.

    Args:
        query  (str):  SQL INSERT query with :param placeholders.
        params (dict): Values to bind to the query placeholders.

    Returns:
        dict with keys:
            - success    (bool): True if insert worked
            - inserted_id (int): The new row's ID
            - message    (str):  Success or error message

    Example:
        run_action(
            "INSERT INTO complaints (customer_id, order_id, product_id, complaint_text) "
            "VALUES (:customer_id, :order_id, :product_id, :complaint_text)",
            {"customer_id": 1, "order_id": 3, "product_id": 3,
             "complaint_text": "Screen has scratches"}
        )
    """
    
    if not is_safe_insert(query):
        return {
            "success":     False,
            "inserted_id": None,
            "message":     "❌ Action blocked: only return requests and complaints can be submitted."
        }

    try:
        engine = get_engine()
        with engine.begin() as conn:   # begin() auto-commits on success
            result = conn.execute(text(query), params or {})
            inserted_id = result.lastrowid

        return {
            "success":     True,
            "inserted_id": inserted_id,
            "message":     f"✅ Action completed. Reference ID: {inserted_id}"
        }

    except Exception as e:
        return {
            "success":     False,
            "inserted_id": None,
            "message":     f"❌ Action failed: {str(e)}"
        }